### ISSUE TITLE
一期 Roadmap

### ISSUE THREAD

**Issue by wewoor** [DTStack/Taier#18]
## 里程碑一、改造 运维中心、数据源、控制台 (2021 7.01 - 2021 07.15） #17 

基于数栈版本：v4.2

- [ ] 导航调整，导出 微应用入口
- [ ] 移除 租户/项目/用户 等不需要的逻辑

详细参考 #17 

## 里程碑二、任务开发 (2021 7.01 - 2021 08.15） #19 

- [ ] 支持 SparkSQL 任务开发
- [ ] 支持基本的 数据同步（关系型数据库 ）

详细参考 #19 

## 里程碑三、发版 Ready (2021 8.15 - 2021 08.30）

全局功能测试（任务/运维/控制台/数据源）

- [ ] 测试数据源管理
- [ ] 测试支持 SparkSQL 任务
- [ ] 测试支持数据同步任务(MySQL，Oracle，SQLServer, PG, HDFS, Hive)
- [ ] 测试基本的任务运维
